package Interfaz;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author Bernardo
 */
public class InterfazCineUnimet extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCineUnimet
     */
    public InterfazCineUnimet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabs = new javax.swing.JTabbedPane();
        PaisesTab = new javax.swing.JPanel();
        PaisLabel = new javax.swing.JLabel();
        AgregarPais = new javax.swing.JButton();
        EscribirPais = new javax.swing.JTextField();
        ListaPaisesLabel = new javax.swing.JLabel();
        ListaPaisesPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaPais100 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaPais200 = new javax.swing.JList();
        SeleccionarPais = new javax.swing.JButton();
        SucursalesTab = new javax.swing.JPanel();
        PaisSeleccionadoLabel = new javax.swing.JLabel();
        PaisSeleccionadoField = new javax.swing.JTextField();
        SucursalesOpciones = new javax.swing.JComboBox();
        SeleccionarSucursal = new javax.swing.JButton();
        InfoSucursalLabel = new javax.swing.JLabel();
        InformacionSucursalPanel = new javax.swing.JPanel();
        DireccionSucursalLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PaisLabel.setText("Ingresar pais:");

        AgregarPais.setText("Agregar");

        EscribirPais.setText("Pais");

        ListaPaisesLabel.setText("Lista de Paises:");

        ListaPaisesPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        ListaPais100.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(ListaPais100);

        ListaPais200.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(ListaPais200);

        javax.swing.GroupLayout ListaPaisesPanelLayout = new javax.swing.GroupLayout(ListaPaisesPanel);
        ListaPaisesPanel.setLayout(ListaPaisesPanelLayout);
        ListaPaisesPanelLayout.setHorizontalGroup(
            ListaPaisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPaisesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        ListaPaisesPanelLayout.setVerticalGroup(
            ListaPaisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListaPaisesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaPaisesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SeleccionarPais.setText("Seleccionar");

        javax.swing.GroupLayout PaisesTabLayout = new javax.swing.GroupLayout(PaisesTab);
        PaisesTab.setLayout(PaisesTabLayout);
        PaisesTabLayout.setHorizontalGroup(
            PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaisesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PaisLabel)
                    .addComponent(EscribirPais, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarPais))
                .addGap(94, 94, 94)
                .addGroup(PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaisesTabLayout.createSequentialGroup()
                        .addComponent(ListaPaisesLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(ListaPaisesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaisesTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SeleccionarPais)
                .addGap(22, 22, 22))
        );
        PaisesTabLayout.setVerticalGroup(
            PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaisesTabLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaisLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ListaPaisesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaisesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaisesTabLayout.createSequentialGroup()
                        .addComponent(EscribirPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarPais))
                    .addComponent(ListaPaisesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(SeleccionarPais)
                .addContainerGap())
        );

        Tabs.addTab("Paises", PaisesTab);

        PaisSeleccionadoLabel.setText("Pais:");

        PaisSeleccionadoField.setBackground(new java.awt.Color(204, 204, 204));

        SucursalesOpciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SeleccionarSucursal.setText("Seleccionar");

        InfoSucursalLabel.setText("Informacion Sucursal");

        InformacionSucursalPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        DireccionSucursalLabel.setText("Direccion:");

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout InformacionSucursalPanelLayout = new javax.swing.GroupLayout(InformacionSucursalPanel);
        InformacionSucursalPanel.setLayout(InformacionSucursalPanelLayout);
        InformacionSucursalPanelLayout.setHorizontalGroup(
            InformacionSucursalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionSucursalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InformacionSucursalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InformacionSucursalPanelLayout.createSequentialGroup()
                        .addComponent(DireccionSucursalLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        InformacionSucursalPanelLayout.setVerticalGroup(
            InformacionSucursalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InformacionSucursalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DireccionSucursalLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout SucursalesTabLayout = new javax.swing.GroupLayout(SucursalesTab);
        SucursalesTab.setLayout(SucursalesTabLayout);
        SucursalesTabLayout.setHorizontalGroup(
            SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SucursalesTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PaisSeleccionadoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PaisSeleccionadoField)
                    .addComponent(SucursalesOpciones, 0, 90, Short.MAX_VALUE))
                .addGroup(SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SucursalesTabLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeleccionarSucursal)
                        .addGap(18, 18, 18)
                        .addComponent(InformacionSucursalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SucursalesTabLayout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(InfoSucursalLabel)
                        .addGap(0, 176, Short.MAX_VALUE)))
                .addContainerGap())
        );
        SucursalesTabLayout.setVerticalGroup(
            SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SucursalesTabLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PaisSeleccionadoLabel)
                    .addComponent(InfoSucursalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SucursalesTabLayout.createSequentialGroup()
                        .addComponent(PaisSeleccionadoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(SucursalesTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SucursalesOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeleccionarSucursal)))
                    .addComponent(InformacionSucursalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        Tabs.addTab("Sucursales", SucursalesTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCineUnimet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCineUnimet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCineUnimet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCineUnimet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCineUnimet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarPais;
    private javax.swing.JLabel DireccionSucursalLabel;
    private javax.swing.JTextField EscribirPais;
    private javax.swing.JLabel InfoSucursalLabel;
    private javax.swing.JPanel InformacionSucursalPanel;
    private javax.swing.JList ListaPais100;
    private javax.swing.JList ListaPais200;
    private javax.swing.JLabel ListaPaisesLabel;
    private javax.swing.JPanel ListaPaisesPanel;
    private javax.swing.JLabel PaisLabel;
    private javax.swing.JTextField PaisSeleccionadoField;
    private javax.swing.JLabel PaisSeleccionadoLabel;
    private javax.swing.JPanel PaisesTab;
    private javax.swing.JButton SeleccionarPais;
    private javax.swing.JButton SeleccionarSucursal;
    private javax.swing.JComboBox SucursalesOpciones;
    private javax.swing.JPanel SucursalesTab;
    private javax.swing.JTabbedPane Tabs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
